name: playwright-integration-test

run-name: Playwright testing - ${{ github.event.inputs.environment || github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment to run tests"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - uat
          - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: |
          echo "Running tests for $ENVIRONMENT"
          set TEST_ENV=$ENVIRONMENT&& npx playwright test 1_SPH_Login_Auth.spec.ts && npx playwright test 2_PDF.spec.ts

      - name: Upload test results (optional)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: playwright-report/
